### ISSUE TITLE
Bug: npx create-prisma-generator doesn't work as intended

### ISSUE THREAD

**Issue by GauravRajSharma** [YassinEldeeb/create-prisma-generator#10]
> (note): Using PopOS 21.0 with node 16.13.1 and npm 7.5.4

Running the `npx create-prisma-generator` command spits out 

```bash
# ....
t̎ͧè̑s̆͂t͒̉́iͯ͊͗n͗͌̎gͣͫ ̎͐tͪ̆ ҉̧̮eͪ̉s͛͛ ҉͚̝̼ẗ͑iͭ͊n̽ͯg̈ͥ ̾̾t̆͑ ҉̵̵͖e̒̅s̊̎t̄̑ͯͧiͤ̒n͆ͪg͑̓ ̂ͩt̿ͩeͪ̓sͤ̋t͌͛ͮi̅ͭnͫ͆̽ ҉̴̯͔͡g͂̎ ̂̎̈ ҉̴̷tͫͬeͯ̚̚s͒ͤ̿t̓͌i̊̈ͯ́n̿̇ͯg̃̄͑ ͮ̐tͪ̑ȇ̌̉ŝͤ ҉̗̣͝ẗ̌̾ ҉̵̧i̔͆̎ ҉̴̪̟n̈̍̿g̋̋ ̽ͤt̅̇ẻ͊sͩͮt͆͛iͫ͛n͛̚ ҉̡̯̘͞g̋̒
tͣ̽ ҉̣͙͢e͋̇s̃͆ ҉̱́͢t̽̊i̐ͮn͒ĝ̚ ̇ͬͩt̐ͥeͬ̽s̆͑t̆̽i͆ͤǹ͒g͂̚ ́ͥt͐́é̈s̃̚t͌̓ǐ̉n̈̅ ҉̱̬͖ġ̽ ͨ̾t̎͒e̓ͮs͆̾ṫͫ̔ȉ͒̐nͫ̇g͊́ ̂ͯt̿͌ ҉̸̢e͐ͦs̋͌t̒ͩ̂i̿̆n̽ͬgͨ́ ̊ͪt̏̅e̒̓s̔ͯt̋ͦîͨ ҉̰͔n̿ͫ̽ĝ̈ ͌ͨͤ ҉̹͚͖̗tͧ͑eͮͪs̈̃ ҉̠͘͝tͬ̾i͊̊nͣͦ ҉͕̝g͑ͩ
ẗͫͬ̓e̔̎s̀ ҉́͞t̆̚i͆̏nͥ̊ḡ̏ ̈ͨt͌̉ͩ ҉̡̧e͋̈ ҉̴̡s̉̀t͑̑ĩ̾̂n̄ͮgͦͤ͐̂̈ ҉̨͕ ̈ͭt͋̓̚ ҉̧͝e͊ͨs͑͒t̔̆iͧ̑ṅ̓g̒͒ ͥ̔͒t̓ͩ͊eͦͮs̈̔ ҉̴͝ẗ͐ ҉̯̩̘iͩ̏̂n͑͂ ҉͘͠gͦ̐ ҉̡̭̭ ̔t͛ͪͮeͯ̔̂sͨ̏ṫ́ ҉̣͙̲̞͢iͧͥnͩ̃g͒ ̈̑t̾̚eͭ̈šͬt̑͋̓i̽̒nͦ̑gͭ͛ ͫ͌t̍̀e͑ͩs͌͆t̐ͫi͛n͋̑ͮg̒̽̈
t͒͑eͯ̿sͣ̉ ҉̵̗͉̫tͧͭ͆ỉ̏̚ñ̏g͗ͯ ̈̾t̎͌̾ȅ̃sͤ͋tͪ͑ͩi͗̔nͭ͌g̍ͯ̚ ҉̱̫̘ ͨ̿t͑̀e̔ͨ̆ͣs̆t̑́i͛̃n̉̍̓gͦ̿͊ ̈̑ẗ̔e̔̄s̈̈̏t͐͊ĭ̈ ҉̻̦nͫͫg͋̚ ͮ̌ť̈ê̓s̒͐t̽͌i͒͗nͫ̋̎ ҉̨͈g̏̂ ҉̝͕͞ ͥ̐̿t͒͒eͧ͂ ҉͈̬͜͜s͒͆t͐̓iͪ̈n̄ͫg͐̒ ̉͐t̊̍ ҉̙̯̦̗̕eͦ͌s̍̂ťͭ ҉̳̼iͮͦn̿ͫgͣ̓
t̔̾e͆̏ ҉̴͍s͒̍t̓͂i̐̊ͪnͫͬgͬͤ ̆̎ ҉͕͍̩̟t̃͗eͯs̓ ҉̡̺tͭ̍ȉ̈̾n̈̔g̐̀ ̊ͪ̃̋ ҉́͢͝t̊̐̑e̐͑s̎ͣ͊ẗͣi̿̄ ҉̸̡̺nͭͤgͥ̃ ͬ̔t͌͆e͋͗s̆͒ ҉ ҉̘̀ẗ͆i͊ͯn̊̉gͨ̍ ҉̸̖͉̕ ͤ͊ ҉̡͠t̀ͩe͗ͧsͯ̇ ҉̛̀ ҉̤̞tͤ̓ͦiͪ̄͒n̾͗gͬͤ ͋͐t̍ͦe̓̋s̍̚t͊͑̒iͣ̈̎nͨͭgͯ̋ ҉̼̀ ͗ͩt͒̉́e̐̉s͑̽t̑̚i͑ͪnͩͦgͣͪ͑
tͯͤêͥsͤ̀t̽̈ỉͭn̈͌ͥg̈ͨ ͐ͦ̍tͣ͂e̐͆s̈͋t̏̾̀i͒͂ͦ̉n͗ͮg̏͛̓ ̋͆t̄̈ȇ͑s͛̽tͣͩi̒͆ͭn̉ͦ ҉̞̬̱̘ḡ͆̈ ͦͧṫͪ̚ȅ̚sͣ̓t̓͒̔̈i̐ͮn̐̂̇ġ̌ ͧ̃t̔̅ ҉͎͉e̐͌ś̆́t̄̈ͥi̅̈ͥn͒̈gͨͬ ͥ̈tͨ͂ě̀s̓ͤtͮ̚i͆͆ ҉̛̘̗̤n͂͂ĝ̾ ̐ͮt̔͗ẻ̒s̀͆t͆͊ȉ̔n̐͒ḡ̃
tͧ́e͑͂ ҉ ҉̧̛̬sͪ̒ ҉̨̻t̅̓ī̓n͆̈ͣgͭ̐ ͪ̇tͯ̎ ҉̵̩̜̀ͅe̓̊s͗͛̅t͛͗́i͆ͪnͭͫg̿͆ ̑̋tͮ̚eͧ̇s͂̓t̒ͤi͗̇n̑ͦg̐̌͒ ҉̵̧ ̉͆t̎̓e͒ͪs̍ͮt̀̉ĩ̾̂n̑ͦĝ͗ ͭ͒̈t́ͭ̒ẽ̈ͥ ҉̵̙̪ͅsͯͣt̎͐i̓̄nͤ̒g̅̈̎ ͩͣẗͨë͐s͂ͤ ҉̳̰t̔̅ ҉̰̀î̚n͒̿gͪ̄̓ ́͗ṫ̊e̐̇sͥͦ̀t͗͑ȉͦ ҉̴͡n̆͛g̏ ҉̵̥
tͦ͑ͭe̒̈̈sͬ̋t͂̔í̚n̏ͧǵ͂ ̆͊t̎̓e͛͂ ҉̡͡ ҉͇̰sͥ̈t͑̈i̎̚n͛̍g̍̂ ͨ̍tͭͣ̋e̒͌̆ ҉̣̲sͣ̓̔t̃ͥͥi̽̂n̋́gͬ ̈̅ ҉͍͍͞t́̔͒ẻ̎sͫt͆ͤiͧͭ̅n̂͒g̿̐ ̍ͩ̈tͦ̅ě̃̋ ҉̫̯s͌́tͩ̉ͬiͧ̓̓ ҉̨̥̹n͒̏g͊ͧ ̊͆t̄ͧ̐eͦͪͣs͂̾t͌̿̚ǐ̏n̉͊ǧ̈ ́̓t̄̚e̓͛sͤtͨ̍iͨͧn̏ͥg̈̋
t͒́e̐̊sͭͯͮtͯ̊i̐̓n͆̓͐gͣ̅́ ̈̃tͬ̈͑eͩ̈̎ ҉̴̨͇̪s͂͌t͑ͭi͋ͤñ̐gͫ̅ ҉̵̝ ͣ͐tͨͨeͣͩ ҉̪͜s̓ͤͤt͋̂i̊̄n͑̽g̔͛ ̅̊t́ͤëͤs̈̇ṫ͗i̓͛nͫ͌ͯ̆g̀̓ ̏͐tͯͯe̓̑s̈͂tͭͨì̊n͊̔g̽̓ ҉̧͕ ͤ͛tͨ͌e̐̇̈s̾̍t͆ͦ̈ȋ̑n̏̔g̍̎ ͥ̒t͗̒e͗ͧs͌ͣ̈ẗ̍͑i̎̒͐ ҉̡̥͜n̿͋́ĝ͒
t͂̓ė̈͋ ҉̶͓͙̟̣̫s̓͐t̀̐ ҉̵̮̠ȋ̀͊̇nͦ̃g̑ͣ͐ ҉̬͍́ ̈́t̏̂e̊̽s̒̊t͆ͧi͗ͦn͊̑gͦ̾ ̍ͩ ҉̤͟t͗͌͑̚ ҉̛͔̣e̐̎s͛̊tͧ̍̏ĩ͊ǹ͌ḡ̏ ͫ̈tͦ̎̄e̅̃ ҉͘͝s̀̂̓t̎͐iͬͧn͑́g̾̓ ͒̒t̀̔ͥe̿ͬsͧ̈t͑̃ĭͮn̆̚ ҉̨̲͠gͦ̚ ̓ͩ̋tͨ̂e͊ͤsͣ̈tͭͦ̐ì̐͊n̎͆g͑̾͒ ͥ̈t̐̍e͛̋sͣ͌tͥ̑i̋͒nͫ͛g͗̓
tͤͥeͤ̂͂ṡ̎ͮt͆͛ĭ͒n͗̊g̽̑̂ ̅̅t͛̾e̊̑ ҉̴̠s̒͂͐ ҉͓͖̭͘t͒ͩiͪ̾n̍̉g͋ͫ͂ ̂̌t͒̽ͪeͦ̓s̅͆t̀̀͆ ҉̴̀i̇ͨńͧg̍̐ ͑̅tͯͯẻͧ ҉̮̰̦̕sͧ͊ ҉͍̫̹t̅͐i̋͋̋n͆͋g͐̄ ̓̚t͋̊ëͭs͐͐ẗ̔i͆ͦn̿̀g̃͊ ͐̎ͩtͥ̑̔ ҉̖̻ếs̄́͑ ҉̧̀ͅt̉ͨí̈ ҉̵̸n͗̚ĝ̌ ͬ̈ẗͧͬe̽͋̈sͧ̀t͋̿̆i͂̊nͦͫgͤ̑
t̄̈̿e̒ͨsͤ̚t͐̔i̐ͧn͆͋g̋ ̈̚tͩ̈eͭ̓sͬͪt̆̽͒i͂n͑̒g͛͆ ͪͨͥtͧ̅eͣ́sͮ̐t̒̃̆i̍͂n̏̔ ҉̨̥gͮͧ͛ ̿ͮt̓͐ ҉͓͙͕e͑͛s̒̉̉tͮ̔ ҉́͘i͑̈n͛̀g̿̄̀ ̃͗t̓̅ẽ͐s̀͊t̀͗iͬ͗ ҉̢͞n͊̑̌g̊͊̈ ́ͤt̓ͪeͫ͛sͨ̐t̽͑i̓̌n͊̓g̀͊ ҉̻̱ ͯͧt̾͂e̊̈s͗͂ͣt͛ͥi͌̃nͭͩğ̈
t̄ͧe̾̾ṡ͛tͮͩi̅͋nͦ̐ ҉̞̬gͩ̍ ̅̽ẗ̈̌ ҉͙͙̮͖eͤͧs̄ͮt̍͗i̓̏nͤ̎ġ̈ ͋̓̑̿t̅̄ë̚sͪ̂ ҉̯͜t̾ͨïͤn̏̔gͦͤ ͒̇ ҉͙̮t̃ͧeͥ̅sͨ̋tͯ͊iͭͣnͧ̋̐̄g͑̽ ͩ̃t͂̍e͌͐s̏̈t̔̾ ҉̵̘ͅi͂͒n̚g̉̎ ̉̀t̓̋eͤ͆ś̆́ ҉̷͕͕̹t͗̋ĭͯn̈ͩg̈̃ ͌̊̅ ҉̤̲͟tͦ̚e͗̇s͊̅ͣtͧïͫnͮͮ̊g̔̀
tͣ̓eͨ̆ ҉̭͇sͮ̆t͛ͥĩ͛ ҉̭̠̦̦͘ń͗͗gͩ̈ ͆̈tͥ̈͂e̓ͧ ҉̣̲̠ͅs͗̽̎͑t͊ͭ ҉̡̳͎̲í̈nͭͦgͭͧ ̅̆ ҉͙̕t͆̄e̿̆ ҉̜̱̠ͅsͯ̆ ҉̣͡tͥͩiͦ͑n͐̃g̀͊ ̓ͩtͫ̓͑ẽ̽s̈ͨt̂͊ǐ̅n̑̃g͛̓̾ ҉͠ ҉̰̖ ̅̄ ҉͖͠tͪ͗e̽̋s̈̓ͯtͥ̽ ҉̹̫iͬ͂nͫ̇gͪ́ ͨ̊t͑̿e͌ͪ ҉̶̖͝s̓͒ ҉̭͇͝t̋̽i̽̾͛ ҉ ҉ ҉̜̘͖͖n̊gͨ̈ ͣ͐ẗ̄eͤ͂̀s̏ͭt̄̓i̎̚nͤ̆g͋̅
# ....
```

and CPU goes to 100%.

**Comment by YassinEldeeb** [comment]
What is this 🤨

**Comment by YassinEldeeb** [comment]
That's super strange cause the e2e tests are passing on both macos and linux [as shown here](https://github.com/YassinEldeeb/create-prisma-generator/runs/4754931788?check_suite_focus=true)

I've never heard of PopOS though so I need more information to dig into this problem.

**Comment by itstheandre** [comment]
> What is this output 🤨
> 
> Was the questions prompt or this is the first thing you saw when you ran `npx create-prisma-generator` ?
> 
> And what kind or hardware do you have to get a 100% CPU usage?

On my side it is literally as soon as the `npx` runs and the package is downloaded, its immediately running like that. 
No question is prompted or anything

**Comment by itstheandre** [comment]
https://user-images.githubusercontent.com/51658452/148700153-35f269ec-f4a5-4ad9-9008-1c9dfdc51890.mov

Here you can see how it looks like in my computer

**Comment by YassinEldeeb** [comment]
WOW! that's crazy

**Comment by YassinEldeeb** [comment]
so actually It's working on the local version before it gets published to npm so It has to be a problem with the npm package tarball on what gets recognized and what's ignored.

![Screenshot 2022-01-09 231234](https://user-images.githubusercontent.com/72823042/148701229-69f11147-85b7-4cb1-b8d5-a8692c5d4bd5.png)

**Comment by itstheandre** [comment]
that is quite confusing really

**Comment by YassinEldeeb** [comment]
oh my godness, It's another thing from @marak in color.js package [in this issue](https://github.com/Marak/colors.js/issues/285)

**Comment by YassinEldeeb** [comment]
Switching to chalk instead of color.js and It should then be working

**Comment by itstheandre** [comment]
> Switching to chalk instead of color.js and It should then be working

let me know when the switch is done and ill let you know if it works here :)

**Comment by DanielRuf** [comment]
You can also use npm / yarn resolutions. I have linked some details in the mentioned issue.

**Comment by YassinEldeeb** [comment]
@DanielRuf Yeah that's a good solution too, but there are a lot of weird stuff going on with @marak open source projects so better step away for a bit of time.

**Comment by YassinEldeeb** [comment]
The new version is out, switched to chalk.js instead of color.js @itstheandre and @GauravRajSharma 

Please let me know If the issue is fixed 🙏

**Comment by itstheandre** [comment]
working!

**Comment by YassinEldeeb** [comment]
I'm really really sorry for the crabby experience you've had for your first time @itstheandre and @GauravRajSharma 😔

**Comment by YassinEldeeb** [comment]
a blog is coming on dev.to to explain the setup you'll get from this CLI and how to develop within it + another one where we're gonna be building a Prisma Generator together 🔥

**Comment by YassinEldeeb** [comment]
why are you doing this @marak ?

https://github.com/Marak/colors.js/issues/285#issuecomment-1008481978
