### ISSUE TITLE
🐛 Bug Report: GitHub Actions should use the chosen package manager

### ISSUE THREAD

**Issue by johannesschobel** [YassinEldeeb/create-prisma-generator#88]
## Bug description

When creating the GitHub Actions, the default package manager that is selected (i.e., `npm`) should be added here as well. The current script, for example, relies on `yarn` and uses the `yarn.lock` file, which is - obviously - not present, if using `npm`.

**Comment by YassinEldeeb** [comment]
Good catch, I'll use the package manager of your choice to install the packages instead.

**Comment by YassinEldeeb** [comment]
Implemented via #89, waiting for the tests to run so that I can merge safely without breaking anything.

**Comment by YassinEldeeb** [comment]
merged! can you confirm if it's working properly now (please wait 5 minutes till the GH workflow is done publishing)

**Comment by johannesschobel** [comment]
Thanks a lot for the fast response and Bugfix.. how can I merge your changes into my existing project? Because your library was used to bootstrap my generator.. or should I bootstrap again and copy my files over?

All the best

**Comment by YassinEldeeb** [comment]
Yeah, I think bootstrapping a new project and copying over the `CI.yml` file, also makes me think of a better way for migrating an existing project cause this is not the ideal way for doing it ;)

Also, I'd be interested to know about your generator in the discussions tab if you've no problem with it.
